### ISSUE TITLE
Failure to create secret when building Android on OSX in Unity Cloud Build

### ISSUE THREAD

**Issue by allan-o3h** [natmlx/natml-unity#56]
Thanks to the updates in 1.1.6 here https://github.com/natmlx/natml-unity/issues/55 I now see an error message when the build fails instead of simply crashing.

```
[error] [2023-05-11T23:59:41Z - Unity] 2023-05-11 16:59:41.853 Unity[9988:76191] NatML Error: Failed to create secret with status: -25300
[2023-05-11T23:59:42Z - Unity] 2023-05-11 16:59:41.959 Unity[9988:76191] NatML Error: Failed to create secret with error: Error Domain=NSOSStatusErrorDomain Code=-25308 "failed to generate asymmetric keypair" (errKCInteractionNotAllowed / errSecInteractionNotAllowed:  / Interaction is not allowed with the Security Server.) UserInfo={numberOfErrorsDeep=0, NSDescription=failed to generate asymmetric keypair}
[2023-05-11T23:59:42Z - Unity] Obtained 256 stack frames.
[2023-05-11T23:59:42Z - Unity] #0  0x007fff227aa0bd in SecKeyCopyPublicKey
[2023-05-11T23:59:42Z - Unity] #1  0x000001609204a2 in NMLModelConfigurationCreateSecret
[2023-05-11T23:59:42Z - Unity] #2  0x00000197f38818 in  (wrapper managed-to-native) NatML.Internal.NatML:CreateSecret (NatML.Internal.NatML/SecretCreationHandler,intptr) [{0x7f8562e1c0b8} + 0xa8]  (0x197f38770 0x197f388bd) [0x118926a80 - Unity Child Domain]
```

So far I've only seen this with Android builds running on OSX in the Unity Cloud Build environment. I haven't run enough builds on Windows to rule out a possible failure there as well, but I'm sure the error will be different if it occurs.

Assuming this is a build environment issue if you have any details on what could be the issue I'll bounce the issue over to Unity.

**Comment by olokobayusuf** [comment]
Gotten a similar report of this. Looking into it.

**Comment by imanirajdoost** [comment]
I have the same error when building AAB for Android using Unity Cloud. The APK builds fine but the AAB fails.

I am using Unity 2021.3.25f1 and building using a Windows OS with default sdk set as Android target sdk.

**Comment by therussmorris** [comment]
Just throwing my hat in the ring and saying I'm experiencing the same issue. Works fine with iOS- fails on Android. Also using OSX as build host.
